### ISSUE TITLE
error: ‘basic_logger_st’ is not a member of ‘spdlog’

### ISSUE THREAD

**Issue by DinkoAtanasov** [leenderthayen/BSG#1]
Using the up-to date spdlog from github gives errors when compiling. 

Checked with the source codes and it seems that the two functions "basic_logger_st" and "stdout_color_st" are under the folder "spdlog/sinks/". This is maybe a workaround but I simply included those in the "NuclearStructureManager.h" and the compilation was successful.

**Comment by leenderthayen** [comment]
Thanks for the notice! I tried reinstalling on a fresh machine a week ago but using the packaged version in ubuntu 18.04 which worked fine.

I'll update the code to reflect the new changes.

**Comment by DWilliamNaim** [comment]
Hey there. Have you updated the code?

I am still having the same problem. 

Cheers

**Comment by DWilliamNaim** [comment]
Just to note I added :

#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/sinks/basic_file_sink.h"

To the NuclearStructureManager.h and it seemed to work as well.

**Comment by leenderthayen** [comment]
This is fixed in the latest version. Closing
