### ISSUE TITLE
Is python 2.7 required?

### ISSUE THREAD

**Issue by DWilliamNaim** [leenderthayen/BSG#2]
Hello,

I was wondering if python 2.7 was required or 3+ works as well? 

Best,
Dan

**Comment by DWilliamNaim** [comment]
I can't seem to install PySide properly. 

" -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/5m/1_8nmh2n3ln1wq0jsr07jp040000gn/T/pip-install-5PGYBx/PySide/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".
    See also "/private/var/folders/5m/1_8nmh2n3ln1wq0jsr07jp040000gn/T/pip-install-5PGYBx/PySide/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken/CMakeFiles/CMakeError.log".
    error: Error configuring shiboken"

I created an environment with Qt 4.8.6 and Py2.7 but still for some reason cannot install Pyside. Any suggestions?

**Comment by DinkoAtanasov** [comment]
> I can't seem to install PySide properly.
> 
> " -- Configuring incomplete, errors occurred!
> See also "/private/var/folders/5m/1_8nmh2n3ln1wq0jsr07jp040000gn/T/pip-install-5PGYBx/PySide/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".
> See also "/private/var/folders/5m/1_8nmh2n3ln1wq0jsr07jp040000gn/T/pip-install-5PGYBx/PySide/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken/CMakeFiles/CMakeError.log".
> error: Error configuring shiboken"
> 
> I created an environment with Qt 4.8.6 and Py2.7 but still for some reason cannot install Pyside. Any suggestions?

I installed PySide from the package manager not relying on pip or the cmake process. Th cmake requirements take a long time to setup. If you work on Ubuntu based OS, a simple "apt install python-pyside" should get from your package manager the proper version.

**Comment by leenderthayen** [comment]
Depending on your system, using a precompiled version of pyside such as the apt package manager is indeed easiest.

Besides this, your error seems to be related to shiboken, but you would have to check the error messages listed you know what's going on.

Note that it is possible to use Qt5 and Pyside 2 (which is still supported, unlike PySide) for the GUI component.
