### ISSUE TITLE
boost::bad_any_cast: failed conversion using boost::any_cast  when running bsg_exec

### ISSUE THREAD

**Issue by stealex** [leenderthayen/BSG#5]
Hello!

  I'm trying to run the code as presented in [https://bsg.readthedocs.io/en/latest/installation.html#execution](https://bsg.readthedocs.io/en/latest/installation.html#execution) after I've followed the installation section. The compilation was successful and I did not run make install in the end.

  The system I'm trying to do this on is Centos7. Any help will be much appreciated.

The fill error is this:

> ERROR: Option "output" not defined. 
> terminate called after throwing an instance of 'boost::bad_any_cast'
>   what():  boost::bad_any_cast: failed conversion using boost::any_cast
> Aborted (core dumped)

Also, the part regarding output is a bit puzzling as I run exactly as described in the link above:
`./bsg_exec -i init/63NI.ini -o 63Ni` from build/bin directory.

Regards,
Stefan

**Comment by wuhongyi** [comment]
Hello,

I run the latest version and have the same issue as Stefan.
I'm tring to do this in CentOS7 and CentOS6.

Best wishes,
Hongyi

**Comment by leenderthayen** [comment]
Hello,

This usually occurs whenever you have specified either on inexistant option or the wrong type for an option, leading boost to spit out a somewhat non-descript error message. This at least has now been 'fixed', in that the code tells you what option was the problem and what values it expects.

It is strange that this happens to an output as basic as 'output'. Can you run the new version of the code and tell me whether it is happening again?

**Comment by wuhongyi** [comment]
Hello,

Thank you very much for your reply.
This issue has been resolved in the latest version.

Best wishes,
Hongyi

![runing](https://user-images.githubusercontent.com/11805461/60723742-14261a00-9f67-11e9-93e7-ac817fc59efb.png)
