### ISSUE TITLE
BSG error for Bismuth212 decay

### ISSUE THREAD

**Issue by plasorak** [leenderthayen/BSG#8]
Hello Leendert

I hope you are well. I was trying to use your tool for generating beta decay spectrum. However when I run it I get the following error message:

```
[2020-04-22 17:54:24.800] [warning] BSG: Configuration file "" cannot be found.
[2020-04-22 17:54:24.803] [warning] NME: Configuration file "" cannot be found.
Calculated b/Ac was NaN. Setting to 0.
Calculated d/Ac was NaN. Setting to 0.
Calculated M121/M101 was NaN. Setting ratio to 0 and M101 to 1.
gsl: qags.c:553: ERROR: bad integrand behavior found in the integration interval
Default GSL error handler invoked.
[1]    13449 abort      ./bsg_exec -i 212Bi.ini -o 212Bi
```

And no spectrum :(

Is this symptomatic of a particular problem? The log isn’t very helpful either…
I’m adding the ini fill at the end of this message.

Thanks!
Pierre

```
[Transition]
#Process can be: B+ (beta+), B- (beta-) or EC (electron capture)
Process=B-
#Type can be Gamow-Teller, Fermi or Mixed
Type=Fermi
#Mixing ratio is defined as g_A M_{GT}/g_V M_F
MixingRatio = 0.0
#Q Value is defined ground-state to ground state Q value in keV
QValue=2251.5

[Mother]
#Proton number of the mother nucleus
Z=83
#Mass number of the mother
A=212
#Mean charge radius in femtometer
Radius=7.15
#Quadrupole and higher-order deformations
# Beta2=0.269
# Beta4=0.182
# Beta6=0.070
#Double of the spin x parity of the nuclear state, always a (negative) integer
SpinParity=1
#Excitation energy relative to the ground state in keV
ExcitationEnergy=250
#Double of isospin of the nuclear state if known, always an integer
# Isospin=1

[Daughter]
Z=84
A=212
Radius=7.15
# Beta2=0.262
# Beta4=0.180
# Beta6=0.025
SpinParity=0
ExcitationEnergy=2922
# Isospin=1
```

**Comment by leenderthayen** [comment]
Hi Paul,

Sorry for taking a while to get back to this. Is it possible that there's an error in your input file? Looking at the Q value, and excitation levels of mother and daughter, there is no energy available to perform the beta decay. 

If this is the case, it's of course not surprising that no spectrum comes out, but the program should probably catch that sooner and output a more helpful error message. These kind of sanity checks are already included in the development version, but not yet in the master version. I'll try to add a quick check in there.

Can you confirm that this is the issue?
Leendert
